apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cgkdemo
  region: ap-southeast-1
managedNodeGroups:
  - name: nodegroup-x86-xlarge
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    volumeSize: 20
    instanceType: t3.xlarge
    ssh:
      allow: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
      nodetype: xlarge
